application: buzzchatbot
version: 1
runtime: python
api_version: 1

handlers:
- url: /google53de00654ebd3aa1.html
  static_files: staticverification/google53de00654ebd3aa1.html
  upload: staticverification/google53de00654ebd3aa1.html
- url: /css
  static_dir: css
- url: /images
  static_dir: images
- url: /.*
  script: main.py

inbound_services:
- xmpp_message